app/solo/urls.py
from django.urls import path

from . import views as steps

app_name = 'solo'

urlpatterns = [
    # Steps
    path('step/<pk>', steps.StepDetailView.as_view(), name='step-detail'),
    path('', steps.StartTemplateView.as_view(), name='home')
]

aventurasolo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Solo
    path('', include('app.solo.urls', namespace='passos'), name='solo')
]

app/solo/models.py
from django.db import models


class Step(models.Model):
    id = models.IntegerField(primary_key=True)
    content = models.TextField()
    nextsteps = models.ManyToManyField('Step', blank=True)

    def __str__(self):
        return str(self.id)

app/solo/views.py
from django.views.generic import DetailView, TemplateView

from app.solo import models


class StepDetailView(DetailView):
    model = models.Step
    template_name = 'step/detail.html'


class StartTemplateView(TemplateView):
    template_name = 'step/home.html'

solo/views.py
from django.views.generic import DetailView, TemplateView

from solo import models


class StepDetailView(DetailView):
    model = models.Step
    template_name = 'step/detail.html'


class StartTemplateView(TemplateView):
    template_name = 'step/home.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>{% block title %}Início{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <h1>O Guerreiro e o Dragão</h1>
    <div id="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/step/detail.html
{% extends '../base.html' %}

{% block title %}
    {% if object.id == 0 %}
        Começo
    {% else %}
        Passo {{object}}
    {% endif %}
{% endblock %}

{% block content %}
    <p>{{ object.content }}</p>
    <div id="options">
    {% for opcao in object.nextsteps.all %}
        {% if opcao.id == 0 %}
            <a href="{% url 'solo:step-detail' opcao.id %} ">Recomeçar</a>
        {% else %}
            <a href="{% url 'solo:step-detail' opcao.id %} ">{{opcao}}</a>
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}

templates/step/home.html
{% extends '../base.html' %}

{% block content %}
    <a href="{% url 'solo:step-detail' 0 %} ">Começar</a>
{% endblock %}